
# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: Home
    title: EERI
    link: homepage
    class: homepage
  - label: News
    link: post
  - label: People
    link: People
  - label: Publications
    link: publication
   
    
